### ISSUE TITLE
Pip Reports Wrong Version

### ISSUE THREAD

**Issue by rcraverii** [NOAA-MDL/GIFTs#29]
Pip reports version 1.0.0 is installed when installed from the tagged version 1.3.0.

1. Install GIFTs from the tagged 1.3.0 version according to the README.
2. Execute 'pip list' to see the GIFTs reported version.

pip should report the GIFTs version as 1.3.0.

Below is an example reported by pip after GIFTs v1.3.0 installed.

$ pip list
Package    Version
---------- ---------
...
gifts      1.0.0
...
skyfield   1.40
...

**Comment by mgoberfield** [comment]
Thank you Rob for the report. The underlying files should be in sync with tags so that the pip utility reports the correct version even though pip is not used for installing this software.
